FROM ghcr.io/graalvm/graalvm-community:24.0.2-ol9 AS builder

RUN microdnf install -y findutils

WORKDIR /app

COPY build.gradle .
COPY settings.gradle .
COPY gradle.properties .
COPY gradlew .
COPY gradle gradle
COPY src src

RUN chmod +x gradlew
RUN ./gradlew nativeCompile --no-daemon

FROM ghcr.io/graalvm/graalvm-community:24.0.2-ol9

WORKDIR /app

COPY --from=builder /app/build/native/nativeCompile/crfa-metadata-service app

EXPOSE 8080

CMD ["./app"]